version: "3"

services:
  mongo-stack:
    image: hello-world
    links:
      - mongo-db
      - mongo-express

  web:
    container_name: trader-mv
    build: .
    command: uvicorn src.app:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - 8000:8000

  mongo-db:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER} 
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - /docker/volumes/mongodb:/data/db # If you're using macos you need to go: docker dashboard -> settings -> resources -> file sharing -> add volume path

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGOEXPRESS_USER} 
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGOEXPRESS_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGODB_URL_IN_DOCKER}
    depends_on:
      - mongo-db
