version: "3"

services:
  web:
    container_name: trader-mv
    build: .
    command: uvicorn src.app:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - 8000:8000